### ISSUE TITLE
New articles not in the commit list

### ISSUE THREAD

**Issue by SebastienElet** [nfroidure/blog#18]
I'm a gentledev i:
[x] fully read the README recently
[x] searched for existing issues
[x] checked i'm up to date with the latest version of the project

### Expected behavior

See the latest articles on the git history

### Actual behavior

The last articles are not on git

### Debugging informations
- `node -v` result:
```
v6.9.5
```

- `npm -v` result:
```
3.10.10
```

**Comment by nfroidure** [comment]
Sorry, just forgot to git push :/.

Done!

**Comment by SebastienElet** [comment]
Then you publish gh-pages from you laptop ? It should be done from the CI in my opinion

**Comment by SebastienElet** [comment]
Nice it is in #19 :-)

**Comment by nfroidure** [comment]
;) Time always lacks but it is a true issue, it is just a few lines in the circle.yml file.
